inputs:
  bucket_name:
    description: GCS bucket name
    required: true
  lb_name:
    description: Load balancer name
    required: true

runs:
  using: Composite
  steps:
    # ダミーファイルをアップロードしてからバケットの中身を削除（バケットの中身が空の場合、gsutil rmでエラーが発生する）
    - name: 【DEV】Refresh bucket
      shell: bash
      run: |
        touch ./dummy.txt
        gsutil cp ./dummy.txt gs://${{ inputs.bucket_name }}
        gsutil rm -a gs://${{ inputs.bucket_name }}/**
        rm -r ./dummy.txt

    # ビルド成果物をバケットにアップロード
    - name: 【DEV】Upload files from dist
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ./dist
        destination: ${{ inputs.bucket_name }}
        parent: false

    # キャッシュクリア
    - name: 【DEV】Invalidate cache
      shell: bash
      run: gcloud compute url-maps invalidate-cdn-cache ${{ inputs.lb_name }} --path "/*" --async
